/*
 * Copyright (c) 2024 Rob Perry
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.intellisiem.core.domain.models;

import jakarta.validation.constraints.NotBlank;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents the source of an asset in the IntelliSIEM system.
 * Sources may include scanning tools like Nmap or Nessus.
 *
 * <p>This entity is mapped to the 'asset_source' table in the database.</p>
 */
public class AssetSource {

    private static final Logger LOGGER = LoggerFactory.getLogger(AssetSource.class);

    /**
     * The unique identifier for the asset source.
     * This is the primary key and is auto-incremented.
     */
    private final Integer id;

    /**
     * The name of the source (e.g., "Nmap"). Cannot be blank and must be unique.
     */
    @NotBlank(message = "Source name cannot be blank.")
    private String name;

    /**
     * A description of the source. Optional.
     */
    private String description;

    /**
     * The timestamp when the source was created.
     * This value is set automatically on creation.
     */
    private final LocalDateTime createdAt;

    /**
     * Default constructor
     */
    public AssetSource() {
        this.id = null; // ID is generated by the database
        this.createdAt = LocalDateTime.now(); // Ensure immutability
        LOGGER.debug("AssetSource entity initialized with default constructor.");
    }

    /**
     * Constructor with parameters
     *
     * @param name the name of the asset source (must not be blank).
     * @param description the description of the asset source
     */
    public AssetSource(String name, String description) {
        if (name == null || name.trim().isEmpty()) {
            LOGGER.error("Asset source name cannot be null or blank when creating AssetSource.");
            throw new IllegalArgumentException("Asset source name cannot be null or blank when creating AssetSource.");
        }
        this.id = null; // ID is generated by the database
        this.name = name;
        this.description = description;
        this.createdAt = LocalDateTime.now(); // Ensure immutability
        LOGGER.debug("AssetSource entity initialized with name '{}' and description '{}'.", name, description);
    }

    // Getters and setters

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            LOGGER.error("Attempted to set a null or blank source name on AssetSource.");
            throw new IllegalArgumentException("Attempted to set a null or blank source name on AssetSource.");
        }
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AssetSource that)) return false;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "AssetSource{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
